def iniciar_menu():
    print("\n" + "="*50)
    print("           CALCULADORA DE MATRICES")
    print("="*50)
    print("1. Sumar matrices")
    print("2. Restar matrices")
    print("3. Multiplicar matrices")
    print("4. Producto Hadamard")
    print("5. Sumar escalar")
    print("6. Restar escalar")
    print("7. Multiplicar por escalar")
    print("8. Dividir por escalar")
    print("9. Determinante")
    print("10. Adjunta")
    print("11. Inversa")
    print("12. Traza")
    print("13. Transpuesta")
    print("14. Salir")
    print("="*50)